# Imagemagick module schema

# Schema for settings.
imagemagick.settings:
  type: config_object
  label: 'Imagemagick settings'
  mapping:
    quality:
      type: integer
      label: 'Image quality'
    binaries:
      type: string
      label: 'Graphics package - ImageMagick/GraphicsMagick'
    path_to_binaries:
      type: string
      label: 'Path to the binaries'
    prepend:
      type: string
      label: 'Prepend arguments'
    debug:
      type: boolean
      label: 'Display debugging information'
    use_identify:
      type: boolean
      label: 'Use identify command'
    locale:
      type: string
      label: 'Locale for escaping shell commands'
    image_formats:
      type: sequence
      sequence:
        type: imagemagick.image_format
    advanced:
      type: mapping
      label: 'Advanced settings'
      mapping:
        density:
          type: integer
          label: 'Image resolution'
        colorspace:
          type: string
          label: 'Convert colorspace'
        profile:
          type: string
          label: 'Color profile path'
    parse_caching:
      type: mapping
      label: 'Settings for image parse caching'
      mapping:
        enabled:
          type: boolean
          label: 'Enable image parse caching'
        expiration:
          type: integer
          label: 'Cache entry duration'
        disallowed_paths:
          type: sequence
          label: 'Paths to be excluded from caching'
          sequence:
            type: string
